# Generated by Django 5.2.2 on 2025-06-09 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('center', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
