# Generated by Django 5.2.2 on 2025-06-27 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_marketproduct'),
        ('products', '0002_remove_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketStok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='markets.market')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_stocks', to='products.product')),
            ],
            options={
                'unique_together': {('market', 'product')},
            },
        ),
    ]
