# Generated by Django 5.2.2 on 2025-07-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0005_alter_marketproduct_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketproductmovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out')], max_length=10),
        ),
    ]
