# Generated by Django 5.2.2 on 2025-07-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0006_alter_marketproductmovement_movement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketproductmovement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
