# Generated by Django 5.2.2 on 2025-07-26 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0008_stocksession'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksession',
            name='stock_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='markets.stocksession'),
        ),
    ]
