# Generated by Django 5.2.2 on 2025-07-26 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0009_stocksession_stock_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocksession',
            name='stock_session',
        ),
        migrations.AddField(
            model_name='marketproductmovement',
            name='stock_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='markets.stocksession'),
        ),
    ]
