# Generated by Django 5.2.2 on 2025-07-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0002_user_created_by_center_user_is_cash_desk_accses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_price_accses',
            field=models.BooleanField(default=False),
        ),
    ]
