# Generated by Django 5.2.2 on 2025-06-09 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0002_rolepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_system.rolepermission')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('worker', 'permission')},
            },
        ),
    ]
