# Generated by Django 5.2.2 on 2025-06-09 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0003_workerpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerpermission',
            name='center',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
