# Generated by Django 5.2.2 on 2025-06-16 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0005_user_created_by_center'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_market',
            new_name='is_market_worker',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_by_center',
        ),
        migrations.AddField(
            model_name='user',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_workers', to=settings.AUTH_USER_MODEL),
        ),
    ]
