# Generated by Django 5.2.2 on 2025-06-17 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0006_rename_is_market_user_is_market_worker_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_market_worker',
            new_name='is_market',
        ),
        migrations.RemoveField(
            model_name='user',
            name='center',
        ),
        migrations.AddField(
            model_name='user',
            name='created_by_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
