# Generated by Django 5.2.2 on 2025-07-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashDesk', '0002_sale_is_counted'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='returned_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
