# Generated by Django 5.2.2 on 2025-07-06 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashDesk', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
