# Generated by Django 5.2.2 on 2025-07-06 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_product_creator'),
    ]

    operations = [
    ]
