# Generated by Django 5.2.2 on 2025-07-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productpricechange'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='update',
            field=models.BooleanField(default=False),
        ),
    ]
