# Generated by Django 5.2.2 on 2025-07-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_supplier_created_by_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='update',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
