# Generated by Django 5.2.4 on 2025-08-02 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
