# Generated by Django 5.2.4 on 2025-08-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_product_unit_delete_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_weighted',
            field=models.BooleanField(default=False, help_text='Is this product sold by weight?'),
        ),
    ]
